#!/usr/bin/env python3
"""
Import inferred line connections from connections.csv into the database.
This script reads the connections generated by infer_connections.py and stores them
in the line_connection table for visualization and analysis.
"""

import csv
from pathlib import Path
from app import app, db
from models import LineConnection

def import_connections_from_csv(csv_file='connections.csv'):
    """
    Import connections from CSV file into database.
    CSV format: From_Bus,To_Bus,Connection_Type,Feeder,Circuit
    """
    
    if not Path(csv_file).exists():
        print(f"❌ File not found: {csv_file}")
        return
    
    with app.app_context():
        print("=" * 70)
        print("📊 IMPORTING LINE CONNECTIONS FROM CSV")
        print("=" * 70)
        print()
        
        # Clear existing connections (optional - uncomment to reset)
        # LineConnection.query.delete()
        # db.session.commit()
        # print("✓ Cleared existing connections\n")
        
        imported = 0
        skipped = 0
        duplicates = 0
        errors = 0
        
        try:
            with open(csv_file, 'r', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                
                for row_num, row in enumerate(reader, start=2):  # start=2 because header is row 1
                    try:
                        from_bus = (row.get('From_Bus') or '').strip()
                        to_bus = (row.get('To_Bus') or '').strip()
                        connection_type = (row.get('Connection_Type') or '').strip()
                        feeder = (row.get('Feeder') or '').strip() or None
                        circuit = (row.get('Circuit') or '').strip() or None
                        
                        # Validate required fields
                        if not from_bus or not to_bus or not connection_type:
                            print(f"⚠️  Row {row_num}: Missing required fields (from_bus, to_bus, or connection_type)")
                            skipped += 1
                            continue
                        
                        # Check for existing connection
                        existing = LineConnection.query.filter_by(
                            from_bus=from_bus,
                            to_bus=to_bus,
                            connection_type=connection_type
                        ).first()
                        
                        if existing:
                            duplicates += 1
                            continue
                        
                        # Create new connection
                        connection = LineConnection(
                            from_bus=from_bus,
                            to_bus=to_bus,
                            connection_type=connection_type,
                            feeder=feeder,
                            circuit=circuit
                        )
                        
                        db.session.add(connection)
                        imported += 1
                        
                        # Commit every 100 rows to avoid memory issues
                        if imported % 100 == 0:
                            db.session.commit()
                            print(f"  Processed {imported} connections...")
                    
                    except Exception as e:
                        print(f"❌ Row {row_num}: {str(e)}")
                        errors += 1
                
                # Final commit
                db.session.commit()
        
        except Exception as e:
            print(f"❌ Error reading file: {str(e)}")
            db.session.rollback()
            return
        
        print()
        print("=" * 70)
        print("✅ IMPORT COMPLETE")
        print("=" * 70)
        print(f"✓ Imported: {imported}")
        print(f"⊘ Duplicates: {duplicates}")
        print(f"⚠️  Skipped: {skipped}")
        print(f"❌ Errors: {errors}")
        print()
        
        # Show statistics
        total = LineConnection.query.count()
        by_type = db.session.query(
            LineConnection.connection_type,
            db.func.count(LineConnection.id)
        ).group_by(LineConnection.connection_type).all()
        
        print("📈 Database Statistics:")
        print(f"   Total connections in database: {total}")
        print(f"   By type:")
        for conn_type, count in sorted(by_type):
            print(f"     • {conn_type}: {count}")
        print()

if __name__ == '__main__':
    import_connections_from_csv()
