"""add_upload_history

Revision ID: b442bb955f7c
Revises: 421aca01d29e
Create Date: 2026-03-11 12:17:58.911946

"""
from alembic import op
import sqlalchemy as sa


revision = 'b442bb955f7c'
down_revision = '421aca01d29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.String(length=128), nullable=False),
    sa.Column('pole_number', sa.String(length=128), nullable=True),
    sa.Column('bus_description', sa.String(length=128), nullable=True),
    sa.Column('bus_type', sa.String(length=64), nullable=True),
    sa.Column('nominal_voltage', sa.Float(), nullable=True),
    sa.Column('feeder', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bus_node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bus_node_bus_id'), ['bus_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_bus_node_feeder'), ['feeder'], unique=False)
        batch_op.create_index(batch_op.f('ix_bus_node_pole_number'), ['pole_number'], unique=False)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('customer_type', sa.String(length=64), nullable=True),
    sa.Column('service_voltage', sa.String(length=32), nullable=True),
    sa.Column('phase', sa.String(length=32), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_customer_id'), ['customer_id'], unique=True)

    op.create_table('latlongdata',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('secondary_service_drop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_drop_id', sa.String(length=128), nullable=True),
    sa.Column('from_bus_id', sa.String(length=64), nullable=True),
    sa.Column('to_customer_id', sa.String(length=64), nullable=True),
    sa.Column('phasing', sa.String(length=10), nullable=True),
    sa.Column('installation_type', sa.String(length=64), nullable=True),
    sa.Column('length_meters_1', sa.Float(), nullable=True),
    sa.Column('length_meters_2', sa.Float(), nullable=True),
    sa.Column('conductor_type', sa.String(length=32), nullable=True),
    sa.Column('conductor_size', sa.String(length=32), nullable=True),
    sa.Column('conductor_unit', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secondary_service_drop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secondary_service_drop_from_bus_id'), ['from_bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secondary_service_drop_service_drop_id'), ['service_drop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secondary_service_drop_to_customer_id'), ['to_customer_id'], unique=False)

    op.create_table('series_inductor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inductor_id', sa.String(length=64), nullable=True),
    sa.Column('from_bus_id', sa.String(length=64), nullable=True),
    sa.Column('to_bus_id', sa.String(length=64), nullable=True),
    sa.Column('phase_type', sa.String(length=32), nullable=True),
    sa.Column('phasing', sa.String(length=32), nullable=True),
    sa.Column('voltage_rating_kv', sa.Float(), nullable=True),
    sa.Column('resistance_a', sa.Float(), nullable=True),
    sa.Column('resistance_b', sa.Float(), nullable=True),
    sa.Column('resistance_c', sa.Float(), nullable=True),
    sa.Column('reactance_a', sa.Float(), nullable=True),
    sa.Column('reactance_b', sa.Float(), nullable=True),
    sa.Column('reactance_c', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series_inductor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_inductor_from_bus_id'), ['from_bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_inductor_inductor_id'), ['inductor_id'], unique=False)

    op.create_table('shunt_capacitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacitor_id', sa.String(length=64), nullable=True),
    sa.Column('bus_connected_id', sa.String(length=64), nullable=True),
    sa.Column('phase_type', sa.String(length=32), nullable=True),
    sa.Column('phasing', sa.String(length=32), nullable=True),
    sa.Column('voltage_rating_kv', sa.Float(), nullable=True),
    sa.Column('kvar_rating_a', sa.Float(), nullable=True),
    sa.Column('kvar_rating_b', sa.Float(), nullable=True),
    sa.Column('kvar_rating_c', sa.Float(), nullable=True),
    sa.Column('power_loss_watts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shunt_capacitor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shunt_capacitor_bus_connected_id'), ['bus_connected_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shunt_capacitor_capacitor_id'), ['capacitor_id'], unique=False)

    op.create_table('shunt_inductor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inductor_id', sa.String(length=64), nullable=True),
    sa.Column('bus_connected_id', sa.String(length=64), nullable=True),
    sa.Column('phase_type', sa.String(length=32), nullable=True),
    sa.Column('phasing', sa.String(length=32), nullable=True),
    sa.Column('voltage_rating_kv', sa.Float(), nullable=True),
    sa.Column('resistance_a', sa.Float(), nullable=True),
    sa.Column('resistance_b', sa.Float(), nullable=True),
    sa.Column('resistance_c', sa.Float(), nullable=True),
    sa.Column('reactance_a', sa.Float(), nullable=True),
    sa.Column('reactance_b', sa.Float(), nullable=True),
    sa.Column('reactance_c', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shunt_inductor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shunt_inductor_bus_connected_id'), ['bus_connected_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shunt_inductor_inductor_id'), ['inductor_id'], unique=False)

    op.create_table('upload_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voltage_regulator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulator_id', sa.String(length=64), nullable=True),
    sa.Column('from_bus_id', sa.String(length=64), nullable=True),
    sa.Column('to_bus_id', sa.String(length=64), nullable=True),
    sa.Column('regulated_bus_id', sa.String(length=64), nullable=True),
    sa.Column('phase_type', sa.String(length=32), nullable=True),
    sa.Column('phasing', sa.String(length=32), nullable=True),
    sa.Column('phase_sense', sa.String(length=32), nullable=True),
    sa.Column('kva_rating', sa.Float(), nullable=True),
    sa.Column('kv_rating', sa.Float(), nullable=True),
    sa.Column('target_voltage', sa.Float(), nullable=True),
    sa.Column('bandwidth', sa.Float(), nullable=True),
    sa.Column('r_setting_a', sa.Float(), nullable=True),
    sa.Column('r_setting_b', sa.Float(), nullable=True),
    sa.Column('r_setting_c', sa.Float(), nullable=True),
    sa.Column('x_setting_a', sa.Float(), nullable=True),
    sa.Column('x_setting_b', sa.Float(), nullable=True),
    sa.Column('x_setting_c', sa.Float(), nullable=True),
    sa.Column('primary_current_rating', sa.Float(), nullable=True),
    sa.Column('pt_ratio', sa.Float(), nullable=True),
    sa.Column('no_load_loss_kw', sa.Float(), nullable=True),
    sa.Column('exciting_current_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voltage_regulator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voltage_regulator_regulator_id'), ['regulator_id'], unique=False)

    op.create_table('energy_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('billing_period', sa.String(length=64), nullable=True),
    sa.Column('kwh_consumed', sa.Float(), nullable=True),
    sa.Column('power_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('energy_consumption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_consumption_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('distribution_transformer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distribution_transformer_to_secondary_bus_id'), ['to_secondary_bus_id'], unique=False)

    with op.batch_alter_table('line_connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phasing', sa.String(length=32), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('pole_number',
               existing_type=sa.String(length=32),
               nullable=False)
        batch_op.drop_constraint('uq_post_pole_number', type_='unique')
        batch_op.create_index(batch_op.f('ix_post_pole_number'), ['pole_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_pole_number'))
        batch_op.create_unique_constraint('uq_post_pole_number', ['pole_number'])
        batch_op.alter_column('pole_number',
               existing_type=sa.String(length=32),
               nullable=True)

    with op.batch_alter_table('line_connection', schema=None) as batch_op:
        batch_op.drop_column('phasing')

    with op.batch_alter_table('distribution_transformer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distribution_transformer_to_secondary_bus_id'))

    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('energy_consumption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_consumption_customer_id'))

    op.drop_table('energy_consumption')
    with op.batch_alter_table('voltage_regulator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voltage_regulator_regulator_id'))

    op.drop_table('voltage_regulator')
    op.drop_table('upload_history')
    with op.batch_alter_table('shunt_inductor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shunt_inductor_inductor_id'))
        batch_op.drop_index(batch_op.f('ix_shunt_inductor_bus_connected_id'))

    op.drop_table('shunt_inductor')
    with op.batch_alter_table('shunt_capacitor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shunt_capacitor_capacitor_id'))
        batch_op.drop_index(batch_op.f('ix_shunt_capacitor_bus_connected_id'))

    op.drop_table('shunt_capacitor')
    with op.batch_alter_table('series_inductor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_inductor_inductor_id'))
        batch_op.drop_index(batch_op.f('ix_series_inductor_from_bus_id'))

    op.drop_table('series_inductor')
    with op.batch_alter_table('secondary_service_drop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secondary_service_drop_to_customer_id'))
        batch_op.drop_index(batch_op.f('ix_secondary_service_drop_service_drop_id'))
        batch_op.drop_index(batch_op.f('ix_secondary_service_drop_from_bus_id'))

    op.drop_table('secondary_service_drop')
    op.drop_table('latlongdata')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_customer_id'))

    op.drop_table('customer')
    with op.batch_alter_table('bus_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_node_pole_number'))
        batch_op.drop_index(batch_op.f('ix_bus_node_feeder'))
        batch_op.drop_index(batch_op.f('ix_bus_node_bus_id'))

    op.drop_table('bus_node')
    # ### end Alembic commands ###
