"""Sync upload provenance columns

Revision ID: c120a4afa653
Revises: 0cdef3a879ad
Create Date: 2026-03-16 16:07:27.521977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c120a4afa653'
down_revision = '0cdef3a879ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_point')
    op.drop_table('connection')
    with op.batch_alter_table('bus_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bus_node_upload_id'))
        batch_op.create_index(batch_op.f('ix_bus_node_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('bus_post_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bus_post_mapping_upload_id'), ['upload_id'], unique=False)
        batch_op.create_foreign_key(None, 'upload_history', ['upload_id'], ['id'])

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_customer_upload_id'))
        batch_op.create_index(batch_op.f('ix_customer_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('distribution_line_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_distribution_line_segment_upload_id'))
        batch_op.create_index(batch_op.f('ix_distribution_line_segment_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('distribution_transformer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_distribution_transformer_upload_id'))
        batch_op.create_index(batch_op.f('ix_distribution_transformer_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('energy_consumption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_energy_consumption_upload_id'))
        batch_op.create_index(batch_op.f('ix_energy_consumption_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('line_connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_line_connection_upload_id'))
        batch_op.create_index(batch_op.f('ix_line_connection_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('load_curve', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_load_curve_upload_id'))
        batch_op.create_index(batch_op.f('ix_load_curve_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_post_upload_id'))
        batch_op.create_index(batch_op.f('ix_post_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('secondary_line_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_secondary_line_segment_upload_id'))
        batch_op.create_index(batch_op.f('ix_secondary_line_segment_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('secondary_service_drop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_secondary_service_drop_upload_id'))
        batch_op.create_index(batch_op.f('ix_secondary_service_drop_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('series_inductor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_series_inductor_upload_id'))
        batch_op.create_index(batch_op.f('ix_series_inductor_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('shunt_capacitor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_shunt_capacitor_upload_id'))
        batch_op.create_index(batch_op.f('ix_shunt_capacitor_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('shunt_inductor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_shunt_inductor_upload_id'))
        batch_op.create_index(batch_op.f('ix_shunt_inductor_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('voltage_regulator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_voltage_regulator_upload_id'))
        batch_op.create_index(batch_op.f('ix_voltage_regulator_upload_id'), ['upload_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voltage_regulator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voltage_regulator_upload_id'))
        batch_op.create_index(batch_op.f('idx_voltage_regulator_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('shunt_inductor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shunt_inductor_upload_id'))
        batch_op.create_index(batch_op.f('idx_shunt_inductor_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('shunt_capacitor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shunt_capacitor_upload_id'))
        batch_op.create_index(batch_op.f('idx_shunt_capacitor_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('series_inductor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_inductor_upload_id'))
        batch_op.create_index(batch_op.f('idx_series_inductor_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('secondary_service_drop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secondary_service_drop_upload_id'))
        batch_op.create_index(batch_op.f('idx_secondary_service_drop_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('secondary_line_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secondary_line_segment_upload_id'))
        batch_op.create_index(batch_op.f('idx_secondary_line_segment_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_upload_id'))
        batch_op.create_index(batch_op.f('idx_post_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('load_curve', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_load_curve_upload_id'))
        batch_op.create_index(batch_op.f('idx_load_curve_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('line_connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_connection_upload_id'))
        batch_op.create_index(batch_op.f('idx_line_connection_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('energy_consumption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_consumption_upload_id'))
        batch_op.create_index(batch_op.f('idx_energy_consumption_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('distribution_transformer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distribution_transformer_upload_id'))
        batch_op.create_index(batch_op.f('idx_distribution_transformer_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('distribution_line_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distribution_line_segment_upload_id'))
        batch_op.create_index(batch_op.f('idx_distribution_line_segment_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_upload_id'))
        batch_op.create_index(batch_op.f('idx_customer_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('bus_post_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bus_post_mapping_upload_id'))
        batch_op.drop_column('upload_id')

    with op.batch_alter_table('bus_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_node_upload_id'))
        batch_op.create_index(batch_op.f('idx_bus_node_upload_id'), ['upload_id'], unique=False)

    op.create_table('connection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('total_length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('connection_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('connection_pkey'))
    )
    op.create_table('connection_point',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('segment_length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], name=op.f('connection_point_connection_id_fkey')),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('connection_point_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('connection_point_pkey'))
    )
    # ### end Alembic commands ###
